# Lecture 9 in class workbook
Duncan's version
September 20 2018

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2])
a

array([1, 2])

In [4]:
b = np.array([2,3])

In [5]:
a.dot(b)

8

In [6]:
a*b

array([2, 6])

In [18]:
A = np.array([[1 ,3], [4 ,8]])
A

array([[1, 3],
       [4, 8]])

In [9]:
A.dot(b)

array([ 8, 32])

In [11]:
A.transpose()

array([[1, 4],
       [2, 8]])

In [14]:
C = np.arange(0,6,1).reshape([3,2])
C

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
A.dot(C)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [16]:
A.dot(C.transpose())

array([[ 2,  8, 14],
       [ 8, 32, 56]])

In [19]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2.  ,  0.75],
       [ 1.  , -0.25]])

In [20]:
A.dot(Ainv)

array([[1., 0.],
       [0., 1.]])