In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [ ]:
plt.rc('text', usetex=True)
SMALL_SIZE = 16
MEDIUM_SIZE = 18
BIGGER_SIZE = 20

plt.rc('font', size=SMALL_SIZE)          # controls default text sizes
plt.rc('axes', titlesize=BIGGER_SIZE)    # fontsize of the axes title
plt.rc('axes', labelsize=MEDIUM_SIZE)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=SMALL_SIZE)    # fontsize of the x-label ticks
plt.rc('ytick', labelsize=SMALL_SIZE)    # fontsize of the y-label ticks
plt.rc('legend', fontsize=SMALL_SIZE)    # legend fontsize
plt.rc('figure', titlesize=BIGGER_SIZE)  # fontsize of figure

In [ ]:
x = np.arange(0,12,0.01)
y1 = 10+(x-6)**2
y2 = 20+2*(x-4)**2
y3 = 2+10*(x-10)**2

y = np.array([y1, y2, y3]).transpose()
print(y)

In [ ]:
plt.plot(x,y)

plt.xlim(0, 15)
plt.ylim(0, 30)
plt.xlabel(r'$\theta$')
plt.ylabel(r'$f(\theta)$')
plt.title('Multiple functions with global minima')
plt.tight_layout()
plt.savefig('multiple_min.pdf')

In [ ]:
plt.plot(x,y1)

plt.xlabel(r'$\theta$')
plt.ylabel(r'$f(\theta)$')
plt.title('Simple function with global minimum')
plt.tight_layout()
plt.savefig('simple_min.pdf')

In [ ]:
print(0.01*4**6)
print(0.1*(3)**5)
0.5*(x-10)**4

In [ ]:
x = np.arange(2,16,0.01)
y = 10-(x-10)**2+0.2*(x-10)**3+0.05*(x-10)**4

In [ ]:
plt.plot(x,y)

#plt.xlim(0, 15)
#plt.ylim(0, 30)
plt.xlabel(r'$\theta$')
plt.ylabel(r'$f(\theta)$')
plt.title('Function with multiple minima')
plt.tight_layout()
plt.savefig('multiple_extrema.pdf')

In [1]:
import numpy as np

In [5]:
a = np.array([1, 2])
b = np.array([3, 4])

The dot product is:

In [9]:
a.dot(b)

11

Different syntax, same result:

In [10]:
np.dot(a,b)

11

Careful -- basic math operations with the vectors are just element-by-element.

In [24]:
a*b

array([3, 8])

We can do multiplication of matrices and vectors, too:

In [25]:
A = np.arange(1,5).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [27]:
A.dot(a)

array([ 5, 11])

And finally, matrices times matrices returns another matrix:

In [28]:
B = np.arange(4,0,-1).reshape(2,2)
B

array([[4, 3],
       [2, 1]])

In [29]:
A.dot(B)

array([[ 8,  5],
       [20, 13]])

The horizontal dimension of the first must equal the vertical dimension of the second:

In [31]:
C = np.arange(6,0,-1).reshape(3,2)
C

array([[6, 5],
       [4, 3],
       [2, 1]])

In [32]:
A.dot(C)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

To make the dimensions match we can use the `transpose`

In [50]:
A.dot(C.transpose())

array([[16, 10,  4],
       [38, 24, 10]])

The inverse:

In [46]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [47]:
A*Ainv

array([[-2. ,  2. ],
       [ 4.5, -2. ]])

In [48]:
np.dot(A, Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [49]:
np.dot(Ainv,A)

array([[ 1.00000000e+00,  4.44089210e-16],
       [-5.55111512e-17,  1.00000000e+00]])